# Generated by Django 4.0 on 2022-02-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findam', '0004_alter_cs_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='desc',
            field=models.TextField(),
        ),
    ]
