# Generated by Django 4.0 on 2022-02-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findam', '0006_alter_cs_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='rating',
            field=models.FloatField(),
        ),
    ]
