# Generated by Django 4.0 on 2022-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findam', '0008_blockchain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=15)),
                ('rating', models.FloatField()),
                ('certificate', models.BooleanField()),
                ('desc', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneurship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=15)),
                ('rating', models.FloatField()),
                ('certificate', models.BooleanField()),
                ('desc', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Web3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=15)),
                ('rating', models.FloatField()),
                ('certificate', models.BooleanField()),
                ('desc', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
